# Generated by Django 5.2.16 on 2026-07-23 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_schema', models.JSONField()),
                ('output_schema', models.JSONField()),
                ('default_permission', models.CharField(choices=[('always_allow', 'Always allow'), ('requires_approval', 'Requires approval'), ('always_deny', 'Always deny')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tickets', to='external_services.action')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tickets', to='external_services.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=36)),
                ('agent_name', models.CharField(max_length=255)),
                ('toolkit_slug', models.SlugField()),
                ('action_slug', models.SlugField()),
                ('params', models.JSONField()),
                ('outcome', models.CharField(choices=[('executed', 'Executed'), ('denied', 'Denied'), ('pending_approval', 'Pending approval'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('invalid_params', 'Invalid params')], max_length=32)),
                ('ticket_id', models.CharField(blank=True, max_length=36, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['agent_id'], name='external_se_agent_i_a152e4_idx'), models.Index(fields=['toolkit_slug'], name='external_se_toolkit_d2b371_idx'), models.Index(fields=['outcome'], name='external_se_outcome_4721b4_idx')],
            },
        ),
        migrations.AddField(
            model_name='action',
            name='toolkit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='external_services.toolkit'),
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('always_allow', 'Always allow'), ('requires_approval', 'Requires approval'), ('always_deny', 'Always deny')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='external_services.action')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='external_services.agent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agent', 'action'), name='unique_override_per_agent_action')],
            },
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('toolkit', 'slug'), name='unique_action_per_toolkit'),
        ),
    ]
