# Generated by Django 5.2.17 on 2026-08-12 17:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_schema', models.JSONField()),
                ('output_schema', models.JSONField()),
                ('default_permission', models.CharField(choices=[('always_allow', 'Always allow'), ('requires_approval', 'Requires approval'), ('always_deny', 'Always deny')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('secret_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tickets', to='external_services.action')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tickets', to='external_services.agent')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=36)),
                ('agent_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=36)),
                ('user_name', models.CharField(max_length=255)),
                ('toolkit_slug', models.SlugField()),
                ('action_slug', models.SlugField()),
                ('params', models.JSONField()),
                ('outcome', models.CharField(choices=[('executed', 'Executed'), ('denied', 'Denied'), ('pending_approval', 'Pending approval'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('invalid_params', 'Invalid params'), ('execution_failed', 'Execution failed'), ('permission_changed', 'Permission changed')], max_length=32)),
                ('ticket_id', models.CharField(blank=True, max_length=36, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['toolkit_slug'], name='external_se_toolkit_d2b371_idx'), models.Index(fields=['outcome'], name='external_se_outcome_4721b4_idx'), models.Index(fields=['agent_id', '-created_at'], name='external_se_agent_i_a4762b_idx'), models.Index(fields=['user_id', '-created_at'], name='external_se_user_id_bc45a0_idx')],
            },
        ),
        migrations.AddField(
            model_name='action',
            name='toolkit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='external_services.toolkit'),
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('always_allow', 'Always allow'), ('requires_approval', 'Requires approval'), ('always_deny', 'Always deny')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='external_services.action')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='external_services.agent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agent', 'action'), name='unique_override_per_agent_action')],
            },
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('toolkit', 'slug'), name='unique_action_per_toolkit'),
        ),
    ]
