# Generated by Django 5.2.17 on 2026-08-12 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDefault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('default_permission_for_new_actions', models.CharField(choices=[('always_allow', 'Always allow'), ('requires_approval', 'Requires approval'), ('always_deny', 'Always deny')], default='always_allow', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='remote_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='toolkit',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('url', models.URLField(max_length=500)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('protocol_version', models.CharField(blank=True, max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='toolkit',
            name='mcp_server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolkit', to='external_services.mcpserver'),
        ),
        migrations.AddConstraint(
            model_name='toolkit',
            constraint=models.UniqueConstraint(condition=models.Q(('mcp_server__isnull', True)), fields=('slug',), name='unique_builtin_toolkit_slug'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_mcp_server_per_owner'),
        ),
    ]
